DROP database IF EXISTS	character_db;

CREATE DATABASE character_db;

USE character_db;



CREATE TABLE characters (
	id INT AUTO_INCREMENT,
    name varchar(50),
    class varchar(50),
    level INT,
    background varchar(50),
    player_name varchar(50),
    faction varchar(50),
    race varchar(50),
    alignment varchar(50),
    exp INT,
    inspiration INT,
    strength INT,
    dexterity INT,
    constitution INT,
    intelligence INT,
    wisdom INT,
    charisma INT, 
    strength_st INT,
    dexterity_st INT,
    constitution_st INT,
    intelligence_st INT,
    wisdom_st INT,
    charisma_st INT,
    armor_class INT,
    initiative INT,
    speed INT,
    current_hp INT,
    temp_hp INT,
    personality_traits varchar(50),
    ideals varchar(50),
    bonds varchar(50),
    flaws varchar(50),
    attacks_and_spellcasting varchar(200),
    passive_wisdom INT,
    equipment varchar(500),
    features_and_traits varchar(500),
    other_proficiencies_and_languages varchar(500),
    age INT,
    height INT,
    weight INT,
    eyes varchar(50),
    skin varchar(50),
    hair varchar(50),
    acrobatics INT,
    animal_handling INT,
    arcana INT,
    athletics INT,
    deception INT,
    history INT,
    insight INT,
    intimidation INT,
    investigation INT,
    medicine INT,
    nature INT,
    perception INT,
    performance INT,
    persuasion INT,
    religion INT,
    sleight_of_hand INT,
    stealth INT,
    survival INT,
    createdAt TIMESTAMP,
    PRIMARY KEY(id)
);