//Dependencies
const Sequelize = require("sequelize");
const db = require("../config/connection");

//Model
const Character = db.define("character", 
  name: DataType.STRING,
  class: DataType.STRING,
  level: DataType.INT,
  background: DataType.STRING,
  player_name: DataType.STRING,
  faction: DataType.STRING,
  race: DataType.STRING,
  alignment: DataType.STRING,
  exp: DataType.INT,
  inspiration: DataType.STRING,
  strength: DataType.INT,
  dexterity: DataType.INT,
  constitution: DataType.INT,
  intelligence: DataType.INT,
  wisdom: DataType.INT,
  charisma_st: DataType.STRING,
  strength_st: DataType.INT,
  dexterity_st: DataType.INT,
  constitution_st: DataType.INT,
  intelligence_st: DataType.INT,
  wisdom_st: DataType.INT,
  armor_class: DataType.STRING,
  initiative: DataType.STRING,
  speech: DataType.STRING,
  current_hp: DataType.STRING,
  temp_hp: DataType.STRING,
  personality_traits: DataType.STRING,
  ideals: DataType.STRING,
  bonds: DataType.STRING,
  flaws: DataType.STRING,
  attacks_and_spellcasting: DataType.STRING,
  passive_wisdom: DataType.STRING,
  equipment: DataType.STRING,
  features_and_traits: DataType.STRING,
  other_proficiencies_and_languages: DataType.STRING,
  age: DataType.INT,
  height: DataType.INT,
  weight: DataType.INT,
  eyes: DataType.STRING,
  skin: DataType.STRING,
  hair: DataType.STRING,
  acrobatics: DataType.INT,
  animal_handling: DataType.INT,
  arcana: DataType.INT,
  athletics: DataType.INT,
  deception: DataType.INT,
  history: DataType.INT,
  insight: DataType.INT,
  intimidation: DataType.INT,
  investigation: DataType.INT,
  medicine: DataType.INT,
  nature: DataType.INT,
  perception: DataType.INT,
  performance: DataType.INT,
  persuasion: DataType.INT,
  religion: DataType.INT,
  slight_of_hand: DataType.INT,
  stealth: DataType.INT,
  survival: DataType.INT
  //fields will go here once we figure out what they are.
});

module.exports = Character;
